### ISSUE TITLE
两点问题哈

### ISSUE THREAD

**Issue by ted423** [axetroy/anti-redirect#1]
希望能顺便处理下在google搜索时出现这个网站可能会损害你的电脑 的情况

连接会类似这种
https://www.google.co.jp/interstitial?url=http://bbs.3dmgame.com/forum-1816-1.html

还有一个就是Firefox 用greasymonkey的情况下
知乎首页滚动会很卡，操作就是滚轮往下拉，然后按home键返回最上面这样反复操作,其中不定时的滚动会失去效果

但是chrome似乎正常

**Comment by skykiny** [comment]
firefox中greasymonkey的情况+1，同样百度贴吧也会出现滚动卡这个问题

**Comment by axetroy** [comment]
感谢反馈。
- 在google搜索时出现：这个网站可能会损害你的电脑 

> 我没有遇到过，linux和windows都正常..没办法查出什么问题

- firefox下很卡这个问题

> 好吧，脚本本来就是写适配chrome的，firefox只是"顺手"，可以就可以，不可以就算，已经不用firefox好久。
> chrome下肯定是没问题的，目前也没有精力去修复，抱歉

**Comment by ted423** [comment]
现在貌似没对3dm报了，所以对我来说不弄也无所谓
不过搜索
www-gmywowoe.ddttbb.win
还是能看到现象的

不过感觉在https://www.google.com.hk/interstitial?添加个点击继续访问网页的按钮可能相对直接取消谷歌的提示可能会更好一些

所以这个问题还是无视我吧

**Comment by axetroy** [comment]
@ted423 
搜索了，也没看到什么现象,基本能用.
解决办法很简单，搭梯子，上Google.

**Comment by axetroy** [comment]
而且这车，发得我猝不及防，在办公室搜索了这种东西...汗
