### ISSUE TITLE
无法有效的保护隐私

### ISSUE THREAD

**Issue by BugKun** [axetroy/anti-redirect#179]
通过阅读源码和fiddler抓包发现部分网站去除重定向的方法是对要重定向的URL发起请求，然后获取最终的地址。  
其实这样就违背了我使用这个插件的本意了，其实去除重定向最主要的是想保护隐私。  
而通过不经脱敏处理的请求会导致，此请求带上用户的cookies，让搜索引擎认为我们这个账号点击了当前页面所有的搜索结果。  
目前此插件我找到的最全面的去除重定向的插件，希望作者能重视并修复这个问题，提高插件的安全性

**Comment by axetroy** [comment]
发送 HTTP 请求是使用扩展提供的 [GM_xmlhttpRequest](https://www.tampermonkey.net/faq.php?ext=dhdg)

而文档里面也没有说明是否会携带页面的 cookie 发送请求

也没有抓过包...

如果真的连带 cookie 一起发送了，那么我也没有办法

可以去扩展的项目发起 issue

**Comment by BugKun** [comment]
你这边可以解决的，你发起的请求可以覆写cookie

**Comment by BugKun** [comment]
```javascript
GM_xmlhttpRequest({
    method: 'GET',
    url: url,
    headers: {
        'User-agent': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.11) Gecko/20071127 Firefox/2.0.0.11',
        'Accept': 'application/atom+xml,application/xml,text/xml',
        'Cookie': '__utmz=something; __utma=something'
    },
    onload: function(xhr) { cb(xhr.responseText); }
  });
```

**Comment by axetroy** [comment]
已在新版本中完成 279d80c39fe1859b6d9a61e1eb09f6c6e9f9ca7f

不再携带 cookie

如果要有存在这样的情况，再打开 issue
