### ISSUE TITLE
发现极其严重问题

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [axetroy/anti-redirect#198]
脚本会把所有百度文库链接替换为https://wenku.baidu.com/error.html?status=404 ,只能在这个bug修复之前永久关闭脚本了

**Comment by axetroy** [comment]
麻烦给出相应的 URL

**Comment by Smoke-N-Mirrors** [comment]
> 麻烦给出相应的 URL

百度搜索中的文库链接https://www.baidu.com/link?url=ehWF_E03OxvNfi64czFmedLWbV2AyyLryUKZ7xTsCcaBUqy4ZPfr5geAv0HipsULj142e5bQJ7ugV1lfR3jrO7wBnYSFzgn83UZmnVCfAMe&wd=&eqid=d0280708000fde2a000000035e796110, 会被直接替换为https://wenku.baidu.com/error.html?status=404

**Comment by asnldm** [comment]
一个workaround：打开百度快照可显示原始链接，也可能直接跳转成功
