### ISSUE TITLE
百度文库未修复

### ISSUE THREAD

**Issue by KSSnow** [axetroy/anti-redirect#212]

**Comment by Erbzur** [comment]
在Google、Baidu和DogeDoge三个搜索引擎上测试，结果如下：

1. Google: **正常**。
![image](https://user-images.githubusercontent.com/39868528/84111311-3f5b9800-aa59-11ea-9a08-b4dce2e04411.png)

2. Baidu: **异常**。
![image](https://user-images.githubusercontent.com/39868528/84111552-c4df4800-aa59-11ea-8387-6018169d1254.png)

3. DogeDoge: **异常**。
![image](https://user-images.githubusercontent.com/39868528/84111666-01ab3f00-aa5a-11ea-866b-9d1612e14d68.png)

**Comment by wzq126** [comment]
好吧，我也刚反馈了，不知道能不能看到

**Comment by axetroy** [comment]
亲测已解决。

过几天再发布新版本

**Comment by wzq126** [comment]
好的 期待ing




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "axetroy/anti-redirect"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午2:11
收件人:&nbsp;"axetroy/anti-redirect"<anti-redirect@noreply.github.com&gt;;
抄送:&nbsp;"START"<353993567@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [axetroy/anti-redirect] 百度文库未修复 (#212)





 
亲测已解决。
 
过几天再发布新版本
