### ISSUE TITLE
google 失效

### ISSUE THREAD

**Issue by batkiz** [axetroy/anti-redirect#230]
如 [此页面](https://www.google.com/search?newwindow=1&sxsrf=ALeKk030eLKGmYI42p2Vzw26OBYtIfrM_w%3A1589723712058&ei=QELBXt6SA9bj-AaTlYmYBQ&q=what+is+telegram+userbot&oq=what+is+telegram+userbot&gs_lcp=CgZwc3ktYWIQAzoGCCMQJxATOgQIABAKOgYIABAKEB46BggAEAUQHjoICAAQBRAKEB46CAgAEAgQChAeOgYIABAIEB5Q8bIGWIG-BmCJwAZoAXAAeACAAYkCiAH0DJIBBTAuNy4ymAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjespephrvpAhXWMd4KHZNKAlMQ4dUDCAw&uact=5)

![image](https://user-images.githubusercontent.com/21122253/82150419-3f69dd00-988b-11ea-8186-1ab59191d6eb.png)

**Comment by axetroy** [comment]
无法重现，无论是港版还是国际版。

如果有其他人反馈，再进行调查
