### ISSUE TITLE
建议增加Bing的去除重定向

### ISSUE THREAD

**Issue by zjyhjqs** [axetroy/anti-redirect#238]
Bing也是我比较常用的搜索引擎之一.

**Comment by batkiz** [comment]
bing 的搜索结果页似乎是不存在重定向的，可以给个示例吗？

---

如：[sparta搜索结果页](https://www.bing.com/search?q=sparta&qs=n&form=QBLH&sp=-1&pq=sparta&sc=7-6&sk=&cvid=D77C03333B9E406E8E251A05A4C8535C)

![image](https://user-images.githubusercontent.com/21122253/83959760-b1927800-a8b3-11ea-910d-a5ad0f781dff.png)

**Comment by axetroy** [comment]
抱歉，我看了半天，愣是没有看到重定向链接

**Comment by zjyhjqs** [comment]
> bing 的搜索结果页似乎是不存在重定向的，可以给个示例吗？
> 
> 如：[sparta搜索结果页](https://www.bing.com/search?q=sparta&qs=n&form=QBLH&sp=-1&pq=sparta&sc=7-6&sk=&cvid=D77C03333B9E406E8E251A05A4C8535C)
> 
> ![image](https://user-images.githubusercontent.com/21122253/83959760-b1927800-a8b3-11ea-910d-a5ad0f781dff.png)


不好意思, 是我自己搞错了.
我用bing的场合都是直接Win+S搜索 (浏览器打开新标签的话就Google了), 那种情况打开页面会重定向. 
这应该和浏览器无关..
