### ISSUE TITLE
支持站點請求

### ISSUE THREAD

**Issue by hdd60311** [axetroy/anti-redirect#24]
希望添加對https://docs.google.com 的支持

**Comment by axetroy** [comment]
@hdd60311 
能给出一个具体的地址吗，没有看到需要去除重定向的链接

**Comment by hdd60311** [comment]
例如這個吧
https://docs.google.com/spreadsheets/d/1TFcEXMcKrwoIAECIVyBU0GPoSmRqZ7A0VBvqeKYVSww/htmlview#

**Comment by axetroy** [comment]
已支持: https://github.com/axetroy/anti-redirect/commit/c29249772bbe937a6144141b4501dfc9f71a080e

以发布到2.1.0版本
