### ISSUE TITLE
希望能增加秘迹的重定向

### ISSUE THREAD

**Issue by Jiang10086** [axetroy/anti-redirect#251]
[秘迹](https://mijisou.com/)，搜索网址：https://mijisou.com/search?q=%s&category_general=on&time_range=&language=zh-CN&pageno=1,谢谢！脚本已经很好用了，是禁止重定向的集大成者

**Comment by axetroy** [comment]
话说这个搜索引擎，有点要当婊子，又立牌坊的感觉。
