### ISSUE TITLE
希望增加网址

### ISSUE THREAD

**Issue by pyb2000** [axetroy/anti-redirect#254]
qq pc端会做重定向,目标url
http://kisssub.115000.xyz/search.php?keyword=%E5%BF%83%E7%90%86%E6%B5%8B%E9%87%8F%E8%80%85
重定向的url
https://c.pc.qq.com/middlem.html?pfurl=http%3A%2F%2Fkisssub%2E115000%2Exyz%2Fsearch%2Ephp%3Fkeyword%3D%25E5%25BF%2583%25E7%2590%2586%25E6%25B5%258B%25E9%2587%258F%25E8%2580%2585&pfuin=344217494&pfto=qq.msg&type=0&gjlevel=15&gjsublevel=2804&ADUIN=344217494&ADSESSION=1593651157&ADTAG=CLIENT.QQ.5737_AIO.0&ADPUBNO=27010

**Comment by axetroy** [comment]
你好，请给出一个包含跳转链接的页面地址。

**Comment by pyb2000** [comment]
> 你好，请确定一个包含扩展链接的页面地址。
你好,我是从qq客户端点击的url,所以没有这个页面的

**Comment by axetroy** [comment]
> > 你好，请确定一个包含扩展链接的页面地址。
> > 你好,我是从qq客户端点击的url,所以没有这个页面的

这个是浏览器的一个脚本，并不适用客户端打开浏览器跳转页面
