### ISSUE TITLE
安装了自动翻页脚本后，自动翻页加载的都没有去除重定向

### ISSUE THREAD

**Issue by aNightCat** [axetroy/anti-redirect#27]
自动翻页脚本：https://greasyfork.org/zh-CN/scripts/10433-super-preloaderplus-one
第一面都有去除重定向，第二页开始就都没有去除重定向了

![screen_shot20170919163816](https://user-images.githubusercontent.com/17309471/30583257-17621000-9d59-11e7-9769-618a5f4821ea.jpg)

**Comment by axetroy** [comment]
感谢反馈

6ebf396a1f932805e4027a39468cd2e83ded207c

已修复, 等待发布新版本...

**Comment by axetroy** [comment]
@aNightCat 已发布新版@2.3.1, 更新即可

**Comment by aNightCat** [comment]
感谢！
