### ISSUE TITLE
百度贴吧重定向问题

### ISSUE THREAD

**Issue by zir-ChiHo** [axetroy/anti-redirect#277]
贴吧长链接链接文字被替换为网页链接四个字，直链被隐藏，无法正常跳转重定向，希望能修复

**Comment by axetroy** [comment]
请给出一个具体的页面地址，谢谢

**Comment by zir-ChiHo** [comment]
就类似于B站的一条分享链接然后正常会跳转至http://jump2.bdimg.com/safecheck/ 这种开头的所谓安全检查界面，然而开启脚本后是直接提示访问出错，希望能修复，还有新浪微博的t.cn短链最近也会重定向至类似安全界面希望能实现自动跳转

**Comment by axetroy** [comment]
@zir-ChiHo 我知道了

但是我需要一个包含重定向链接的页面，方便我排查问题

毕竟我也精力有限，没能一个一个贴吧去找这样的链接

**Comment by zir-ChiHo** [comment]
https://tieba.baidu.com/p/6917564962?pid=134519695080&cid=0#134519695080 贴吧随便搜的，这这个没有重定向至safecheck但是也是会有问题的，看来是只要变成网页链接四个字的蓝链就会出现这个问题
