### ISSUE TITLE
希望支持 百度百科

### ISSUE THREAD

**Issue by pixiandouban** [axetroy/anti-redirect#331]
### 新的网站支持

> 请输入你想要支持的网站
百度百科
### 相关的连接

> 请填写相关的链接，最好是带有重定向的页面
https://baike.baidu.com/reference/5549800/329b8-b7NPT-TGNw_JPxJtEsh0sk1-1Vxh76EpngTXSSfEJX5PgtdlhijfymfFUkj7mLcsZCwlj5_G3NzQbY7N8XLtHR

来源页面：[豆瓣-百度百科](https://baike.baidu.com/item/%E8%B1%86%E7%93%A3%E7%BD%91)

**Comment by axetroy** [comment]
抱歉，找不到有重定向的链接
