### ISSUE TITLE
希望支持下印象笔记的外链跳转

### ISSUE THREAD

**Issue by xhhjin** [axetroy/anti-redirect#344]
### 新的网站支持

> 印象笔记：https://yinxiang.com/

### 相关的连接

> 需要登录：
https://app.yinxiang.com/OutboundRedirect.action?dest=https%3A%2F%2Fwww.jianshu.com%2Fp%2F4d3ba29ab952

**Comment by axetroy** [comment]
在版本 2.18.0 中已支持
