### ISSUE TITLE
支持网站: CSDN

### ISSUE THREAD

**Issue by AlanMaxxx** [axetroy/anti-redirect#350]
### 新的网站支持

> 希望支持一下CSDN
### 有重定向链接的网页地址

> https://blog.csdn.net/xyisv/article/details/79095649?utm_medium=distribute.pc_relevant_bbs_down.none-task--2~all~sobaiduend~default-2.nonecase&depth_1-utm_source=distribute.pc_relevant_bbs_down.none-task--2~all~sobaiduend~default-2.nonecase

**Comment by axetroy** [comment]
改写反馈，已经支持 CSDN，更新版本后生效
