### ISSUE TITLE
请求支持一下百度学术

### ISSUE THREAD

**Issue by GuannanGuo** [axetroy/anti-redirect#36]
您好，

请求支持一下在百度学术上的反重定向。

比如在如下论文中：
[The information value of online social networks: Lessons from peer-to-peer lending](http://xueshu.baidu.com/s?wd=paperuri%3A%2881bc976701a2966e20f5f1c59d101f7d%29&filter=sc_long_sign&sc_ks_para=q%3DThe%20information%20value%20of%20online%20social%20networks%3A%20Lessons%20from%20peer-to-peer%20lending%20%E2%98%86&sc_us=14762571577320581599&tn=SE_baiduxueshu_c1gjeupa&ie=utf-8)

点击“全部来源”栏下的“Elsevier”，页面会在一个百度学术的内嵌框里打开([http://xueshu.baidu.com/s?wd=paperuri%3A%2881bc976701a2966e20f5f1c59d101f7d%29&filter=sc_long_sign&tn=SE_xueshusource_2kduw22v&sc_vurl=http%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fpii%2FS0167718716302776&ie=utf-8&sc_us=14762571577320581599](http://xueshu.baidu.com/s?wd=paperuri%3A%2881bc976701a2966e20f5f1c59d101f7d%29&filter=sc_long_sign&tn=SE_xueshusource_2kduw22v&sc_vurl=http%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fpii%2FS0167718716302776&ie=utf-8&sc_us=14762571577320581599))，但我实际上只想去Elsevier这篇文章的官网(即[http://www.sciencedirect.com/science/article/pii/S0167718716302776](http://www.sciencedirect.com/science/article/pii/S0167718716302776))。

非常感谢。

**Comment by axetroy** [comment]
@GuannanGuo 
非常感谢提供， 一两天内更新

**Comment by axetroy** [comment]
@GuannanGuo 
已更新, 支持百度学术

**Comment by GuannanGuo** [comment]
我试了一下，好像不行。就是之前给的例子，点击还是没有直接打开文章的官网。

**Comment by GuannanGuo** [comment]
我把第3900行`'data-link'` 改成`'data-url'` 就可以用了。

**Comment by axetroy** [comment]
@GuannanGuo 

嗯， 是为疏忽了， 已经更新了
