### ISSUE TITLE
简书偶尔失效

### ISSUE THREAD

**Issue by saltfishh** [axetroy/anti-redirect#366]
### BUG 描述
简书跳转偶尔失效
> 请对这个 BUG 进行描述

### 相关的连接

> 请输入出现这个 BUG 的相关网页地址

`https://www.jianshu.com/go-wild?ac=2&url=https%3A%2F%2Ftic.gal%2Fen%2Fjava-security-cert-certpathvalidatorexception-trust-anchor-for-certification-path-not-found%2F`
`https://www.jianshu.com/go-wild?ac=2&url=https%3A%2F%2Fletsencrypt.org%2Fzh-cn%2Fdocs%2Frate-limits%2F`
截图如下:
![photo_2021-01-14_21-10-38](https://user-images.githubusercontent.com/44364154/104613939-b2e61780-56c2-11eb-9ad7-503f5c592d64.jpg)

**Comment by axetroy** [comment]
感谢反馈，已修复

**Comment by axetroy** [comment]
感谢反馈，已修复
