### ISSUE TITLE
反重定向链接错误

### ISSUE THREAD

**Issue by aNightCat** [axetroy/anti-redirect#38]
https://www.sogou.com/web?ie=UTF-8&query=%E5%8D%8E%E5%85%B4%E9%93%B6%E8%A1%8C

搜狗搜索”华兴银行“，显示的第一个搜索选项，反重定向url不正确。
正确地址应该是：www.ghbank.com.cn，
但是开启反重定向后变成了：http://mp.weixin.qq.com/s?%3E%E5%B9%BF%E4%B8%9C%3Cem%3E%3C!--red_beg--%3E%E5%8D%8E%E5%85%B4%E9%93%B6%E8%A1%8C%3C!--red_end--%3E%3C/em%3E2018%E5%B9%B4%E5%B7%A5%E4%BD%9C%E4%BC%9A%E8%AE%AE%E5%9C%86%E6%BB%A1%E9%97%AD%E5%B9%95%3C/a%3E%3Cstrong%20class=

![image](https://user-images.githubusercontent.com/17309471/35260416-732721f0-0046-11e8-971a-3595298e6c94.png)

**Comment by axetroy** [comment]
### 这是未开启脚本前的: 

![1](https://user-images.githubusercontent.com/9758711/35260977-151ac974-0049-11e8-9fb4-d8b765d06522.png)

### 这是开启脚本后的样子

![2](https://user-images.githubusercontent.com/9758711/35261004-35904fb2-0049-11e8-821f-7ab9c7bb67c8.png)

解析出来的地址为 **http://www.ghbank.com.cn**

我自己实验的，正常。

抱歉，你的问题我无法复现

**Comment by axetroy** [comment]
问题没有后续，关闭issue
