### ISSUE TITLE
多吉搜索去重定向，部分无效果

### ISSUE THREAD

**Issue by rafaelyine** [axetroy/anti-redirect#384]
### BUG 描述

> 多吉doge搜索去除重定向，部分有效、部分无效果。无论输入什么搜索字符，搜索结果页面基本上都是7成左右链接是能成功去除重定向，但是还有3成左右链接是失效，无法去除重定向。即便是能生效的那7成，很多链接也是要耗费很久时间才能顺利去重定向。与网络无关，同样网络下Google百度都是根本看不到重定向链接。希望作者能改进，感谢！

### 相关的连接

> 请输入出现这个 BUG 的相关网页地址
比如：https://www.dogedoge.com/results?q=%E6%B6%88%E9%98%B2%E4%BA%94%E8%B7%9D
首页正数第1条链接，倒数第2、倒数第6条链接都是无法去除重定向。

**Comment by axetroy** [comment]
抱歉，链接已过期。等待其他人给予反馈
