### ISSUE TITLE
希望支持QQ邮箱和它的Foxmail邮箱

### ISSUE THREAD

**Issue by ChandelierX** [axetroy/anti-redirect#40]
首先肯定你的工作！非常棒，很好地弥补了国外相应脚本缺乏对百度知乎之流的支持的短处。
希望您有时间的话可以加入对QQ邮箱中链接的反重定向，那个真的很烦。会拦截并提醒你什么不要在你打开的网站输入qq密码......
[比如这个](https://mail.qq.com/cgi-bin/readtemplate?t=safety&check=false&gourl=http%3A%2F%2Fwww.cdgdc.edu.cn%2F&subtemplate=gray&evil=0)

您将要访问：
http://www.cdgdc.edu.cn/
建议您不要在该网页输入QQ密码、密保资料等信息。
我们无法确认该网页是否安全，它可能包含未知的安全隐患，或来自一封未知的邮件。为了保护您的QQ帐号安全，请不要在该网页输入您的QQ密码、密保资料等信息。
您也可以安装QQ浏览器，可有效拦截钓鱼和欺诈网站，防止帐号信息被盗。

PS我知道（也在用）很多可以替代QQ和Foxmail邮箱的正经邮箱...但现阶段还是有一点需求。
感谢。

**Comment by axetroy** [comment]
@Chandelier309 
如果这能帮助到你，不妨star一个支持下

下一个版本会支持qq邮箱

**Comment by axetroy** [comment]
已增加qq邮箱的支持

**Comment by axetroy** [comment]
@YiweiNiu 
QQ邮箱更改了重定向规则，失效了
