### ISSUE TITLE
so.com用site:www.baidu.com翻页出错，请检查

### ISSUE THREAD

**Issue by cjjdaq** [axetroy/anti-redirect#42]
so.com用site:www.baidu.com翻页出错，请检查，点第几页会url会这样：
https://www.so.com/s?https://www.so.com/s?q=site%3Awww.baidu.com&pn=2&psid=6f0f33895275ae5518ab7e8f03a25210&fr=none

**Comment by axetroy** [comment]
@cjjdaq 
非常感谢反馈.
已修复, 更新新版本即可.
