### ISSUE TITLE
能去除淘宝搜索的重定向吗

### ISSUE THREAD

**Issue by 649470262** [axetroy/anti-redirect#44]

**Comment by axetroy** [comment]
@649470262 
可以的，但是你能否提供淘宝搜索的页面，说明哪里的重定向

**Comment by 649470262** [comment]
www.taobao.com  淘宝网
s.taobao.com  淘宝搜索
感激不尽

**Comment by axetroy** [comment]
@649470262 
我没有看到哪里有重定向，是否可以具体一点

**Comment by 649470262** [comment]
嗯...我不懂任何编程知识及相关内容，包括重定向，我只是想让点击过的淘宝搜索链接变色，这方法百度一查一大堆，但无一例外，淘宝一刷新，变色的链接就变回原样。目前在我所掌握的知识里，只发现你写的这个脚本+一个改变链接颜色CSS，就可以实现“点击过的链接变色，且刷新也不会重置颜色”，但可惜你的脚本没有应用到淘宝搜索，而我需要的恰恰就是淘宝搜索

**Comment by axetroy** [comment]
@649470262 

这个不是重定向哦，抱歉

**Comment by 649470262** [comment]
那要怎么做？

**Comment by 649470262** [comment]
用你这个脚本，可以实现改变百度搜索的链接颜色，且刷新也不会重置颜色，这个原理不能应用到淘宝搜索吗

**Comment by 649470262** [comment]
有什么办法吗，o(╥﹏╥)o @axetroy

**Comment by axetroy** [comment]
@649470262 
抱歉，没办法

**Comment by 649470262** [comment]
@axetroy 
那为何百度搜索可以实现，淘宝搜索不能实现，是被淘宝方禁止了吗

**Comment by woyaojizhu8** [comment]
@649470262 我的理解：像百度搜索，微信链接，安卓QQ内置浏览器等，有很多都会在URL里加各种参数，记录你的各种信息，淘宝搜索也是。因为你每次点击，有些信息变化了（例如时间），所以URL变了，访问过的链接也就不会变色了（因为URL不完全一样了）。去掉这种参数，不属于去除重定向，跟本脚本主题不符。
