### ISSUE TITLE
适配全站点的建议

### ISSUE THREAD

**Issue by violenttamper** [axetroy/anti-redirect#453]
请问脚本能否考虑做适配全部站点，类似于这个脚本![IMG_20210530_140832.jpg](https://user-images.githubusercontent.com/75355896/120094055-b4cfe500-c150-11eb-9c92-35a5f16e2e0c.jpg)这个脚本的工作原理是不是可以参考下?

**Comment by axetroy** [comment]
感谢反馈，但是这种事没有银弹
