### ISSUE TITLE
知乎去除 redirect 失效

### ISSUE THREAD

**Issue by Ding-Fan** [axetroy/anti-redirect#464]
### BUG 描述

> 请对这个 BUG 进行描述

知乎去除 redirect 失效

### 相关的连接

> 请输入出现这个 BUG 的相关网页地址

https://www.zhihu.com/signin?next=http%3A%2F%2Fwww.zhihu.com%2Fquestion%2F37597646%2Fanswer%2F1961575564

**Comment by axetroy** [comment]
你好，请给出有重定向地址的那个页面

**Comment by Ding-Fan** [comment]
http://www.zhihu.com/question/37597646/answer/1961575564

就是链接里 `next=` 后面的

**Comment by Ding-Fan** [comment]
我尝试把 https://github.com/axetroy/anti-redirect/blob/9c9a92657163ff4a2cb14a3fab01d1ca9aa2d4f3/src/sites/www.zhihu.com.ts#L5 里的 `target=` 改成 `next=` ，不太行，不知道是不是我改错了

**Comment by Young-Lord** [comment]
这个回答是强制要求登陆的，不登陆无法进入，修改url也没用
