### ISSUE TITLE
掘金cn域名不支持

### ISSUE THREAD

**Issue by jeffxjh** [axetroy/anti-redirect#469]
### 新的网站支持

> 请输入你想要支持的网站
https://juejin.cn/
### 有重定向链接的网页地址
https://juejin.cn/post/6844903703908990990
> 请填写有重定向链接的网页地址，方便我定位支持
> 
> 个人精力有限，我不太可能会在网站中一个一个的去找，感谢你的理解
> https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2FYao-JSON%2Fblog
> 否则我大概率不会支持

### 其他说明

> 可选

**Comment by axetroy** [comment]
感谢反馈，已支持
