### ISSUE TITLE
添加 steam 商店支持

### ISSUE THREAD

**Issue by axetroy** [axetroy/anti-redirect#48]
缺少具体的页面

**Comment by DemoJameson** [comment]
Steam 社区的指南里假如使用了外部网址就会被加上重定向，例如：
这个指南 https://steamcommunity.com/sharedfiles/filedetails/?id=1311535531
里的链接https://steamcommunity.com/linkfilter/?url=https://www.instagram.com/theounderstars/

**Comment by axetroy** [comment]
@DemoJameson 感谢反馈，已经支持.
