### ISSUE TITLE
pocket重新定向问题

### ISSUE THREAD

**Issue by maxduke** [axetroy/anti-redirect#49]
发现有时候原链接后面还会formCheck参数，去除重新定向只去除了前部分，很多网站带着formCheck参数跳转后会404。

例如现有脚本处理后的链接：
https://www.appinn.com/firefox-send-released/&formCheck=fe58b45790366f230e30a1b679f54d3b

希望重新定向去除前部分的同时能去除formCheck参数，即&formCheck开始到最后的部分

**Comment by axetroy** [comment]
感谢你的反馈

能不能给个具体的页面，或者未去除跳转前的链接

**Comment by maxduke** [comment]
未启用anti-redirect都情况下
https://getpocket.com/redirect?url=https%3A%2F%2Fwww.appinn.com%2Ffirefox-send-released%2F&formCheck=fe58b45790366f230e30a1b679f54d3b

**Comment by axetroy** [comment]
已解决
