### ISSUE TITLE
能否将脚本上传到国内用户方便访问的地方呢

### ISSUE THREAD

**Issue by DeepChirp** [axetroy/anti-redirect#490]
您好！
GreasyFork上的脚本被删除了，但是GitHub在国内不能直接访问，所以能否将脚本上传到国内用户方便访问的地方呢？`jsDelivr`可能是一个不错的选择。谢谢！

可用的链接：https://cdn.jsdelivr.net/gh/axetroy/anti-redirect@gh-pages/anti-redirect.user.js

**Comment by axetroy** [comment]
GreasyFork 上面玩的就是溜，举报就举报了嘛，点击申诉就 502

后面考虑放在国内的一个 cdn，或者同步到国内的 gitee 也不错

**Comment by Geeyun-JY3** [comment]
和隔壁应该是类似的：https://github.com/machsix/Super-preloader/issues/641
最近 Greasy Fork 不少脚本都是这样被删的。

**Comment by shenzhiming88** [comment]
和我参与维护的一个项目应该也差不多，https://github.com/rxliuli/userjs#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E5%8F%91%E5%B8%83%E5%88%B0-greasyfork-%E4%B8%8A

**Comment by axetroy** [comment]
请使用 CDN 进行加载

https://cdn.jsdelivr.net/gh/axetroy/anti-redirect@gh-pages/anti-redirect.user.js
