### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by luotianyiismywife** [axetroy/anti-redirect#498]
### BUG 描述

> 请对这个 BUG 进行描述
![图片](https://user-images.githubusercontent.com/81459639/132464311-14ac052a-24f5-48f0-8f5a-e5000b2cca25.png)

### 相关的连接

> 请输入出现这个 BUG 的相关网页地址

**Comment by axetroy** [comment]
![截屏2022-04-10 14 20 50](https://user-images.githubusercontent.com/9758711/162605229-cff441c2-ce1b-4b40-af22-4e3baeb82f14.png)

2022/4/10 测试正常，绿色代表已去除重定向
