### ISSUE TITLE
贴吧跳转失效

### ISSUE THREAD

**Issue by yuijker** [axetroy/anti-redirect#560]
### BUG 描述

> 请对这个 BUG 进行描述
在部分新的贴吧链接，点击后跳转的页面会停留在下图这个页面：

![image](https://user-images.githubusercontent.com/72558803/157663353-3b7b714a-4177-423a-9941-1416ac7204a8.png)

### 相关的连接

> 请输入出现这个 BUG 的相关网页地址

例子：http://jump2.bdimg.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxKs8g842PvkehOoBFSwyKurh9IWgNjFzIJvaLoaO/fluPbMR9RMSzi7DNWEkHXixcKtRBeydNXki4TkqUQKxTqQbrJaVqochQrfwdecpJ61PYVSTrcXaD737oefa0/J0Qh2Pah4egTNMg==

上图所在停留页面：http://[tieba.baidu.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxKs8g842PvkehOoBFSwyKurh9IWgNjFzIJvaLoaO/fluPbMR9RMSzi7DNWEkHXixcKtRBeydNXki4TkqUQKxTqQbrJaVqochQrfwdecpJ61PYVSTrcXaD737oefa0/J0Qh2Pah4egTNMg==](http://tieba.baidu.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxKs8g842PvkehOoBFSwyKurh9IWgNjFzIJvaLoaO/fluPbMR9RMSzi7DNWEkHXixcKtRBeydNXki4TkqUQKxTqQbrJaVqochQrfwdecpJ61PYVSTrcXaD737oefa0/J0Qh2Pah4egTNMg==)

**Comment by axetroy** [comment]
Hello，可以提供具体的页面地址吗？

**Comment by yuijker** [comment]
https://tieba.baidu.com/p/7763083667
你要是以为打开时是已经失效的百度网盘分享链接不好的话，从上面的帖子里找一个下载地址去研究吧。

**Comment by axetroy** [comment]
抱歉，我无法重现这个情况，所以只能先关闭
