### ISSUE TITLE
Twitter 失效

### ISSUE THREAD

**Issue by Alphabet1226** [axetroy/anti-redirect#565]
### BUG 描述

>Twitter 的 t.co 无法重定向
![image](https://user-images.githubusercontent.com/51783873/162598882-6b136a93-642c-41fa-a7e7-b04e62620562.png)

### 相关的连接

> https://twitter.com/ftium4/status/1512815116810522631

**Comment by axetroy** [comment]
感谢反馈，已修复，发布在新版 2.19.2 中

**Comment by Alphabet1226** [comment]
突然发现在某些Twitter页面下也会失效，并且会造成链接无法打开。
比如这个：https://twitter.com/liangwenhao3/status/1518105698516746243
