### ISSUE TITLE
无法适配google

### ISSUE THREAD

**Issue by letterk** [axetroy/anti-redirect#572]
### BUG 描述

> 打开google, 不工作, 查看tampermonkey已启用里都没有
> 尝试在用户包括里添加`www.google.com`依然没有无法匹配google
> 百度正常

**Comment by axetroy** [comment]
能给出 google 的域名地址吗，可能是没有匹配到子域名

**Comment by snylonue** [comment]
@axetroy 
`www.google.com` 不生效
![image](https://user-images.githubusercontent.com/48825598/166101975-f1189056-92e4-47d1-bec8-f35a091a1c1f.png)

**Comment by letterk** [comment]
@snylonue 按照你的方法修改是匹配上google了, 但我不知道这个脚本是否起作用. 因为我点击网址的时候, 地址栏依然是`https://www.google.com/url?`的重定向链接

**Comment by letterk** [comment]
谷歌的重定向会在你鼠标指向链接左键或者右键时, 用js重新修改目标地址, 导致ac和这个的去除重定向都不成功. 我用键盘就能打开去除重定向后的网址

**Comment by snylonue** [comment]
> @snylonue 按照你的方法修改是匹配上google了, 但我不知道这个脚本是否起作用. 因为我点击网址的时候, 地址栏依然是`https://www.google.com/url?`的重定向链接

看了下确实没生效

**Comment by axetroy** [comment]
麻烦能否提供一个 google 的页面地址

**Comment by snylonue** [comment]
> 麻烦能否提供一个 google 的页面地址

https://www.google.com/search?q=test
