### ISSUE TITLE
豆瓣帖子重定向失效

### ISSUE THREAD

**Issue by unoni** [axetroy/anti-redirect#587]
### BUG 描述

> 这个帖子会在显示出内容一秒左右直接跳转到豆瓣首页，应该也不是帖子删除了吧，不然根本连内容都不会显示。

### 相关的连接

> 请填写有重定向链接的网页地址，方便我定位排查
> https://www.douban.com/note/774543528/?_i=6300225Zsytufy,6300228Zsytufy
> 个人精力有限，我不太可能会在网站中一个一个的去找，感谢你的理解

**Comment by axetroy** [comment]
无法找到重定向链接
