### ISSUE TITLE
支持网站: 酷安

### ISSUE THREAD

**Issue by hacamer** [axetroy/anti-redirect#588]
### 新的网站支持

> 酷安

### 有重定向链接的网页地址

> https://www.coolapk.com/link?url=https%3A%2F%2Fwww.lanzouj.com%2F
>

### 其他说明

> 酷安是APP，在酷安打开外部链接会有这个重定向

> 目标链接就是url那个部分

> 希望大佬能支持一下，感谢

**Comment by axetroy** [comment]
这个脚本，只作用于网页，不作用于 App。

如果是网页版的酷安有重定向链接，欢迎提供这个页面
