### ISSUE TITLE
支持网站: 谷歌手气不错

### ISSUE THREAD

**Issue by DemoJameson** [axetroy/anti-redirect#596]
### 新的网站支持

谷歌手气不错的搜索：https://www.google.com/search?q=%s&btnI

### 有重定向链接的网页地址

例如搜索 github 将会跳转到 https://www.google.com/url?q=https://github.com/
![image](https://user-images.githubusercontent.com/181192/182756327-ed953d7d-16a8-4d75-9e59-0a88e261ba78.png)

**Comment by axetroy** [comment]
无法重现，麻烦给出一个有重定向连接的页面
