### ISSUE TITLE
请求支持一下腾讯文档

### ISSUE THREAD

**Issue by sherlocknieh** [axetroy/anti-redirect#625]
示例链接：
https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fwww.bilibili.com%2Fvideo%2FBV1Ux411k76Z%3Fspm_id_from%3D333.999.0.0&pid=300000000$aNnVenMuKuyD&cid=144115216090256570

**Comment by axetroy** [comment]
感谢反馈，但是缺少具体的页面。

**Comment by sherlocknieh** [comment]
> 感谢反馈，但是缺少具体的页面。没有足够的信息无法支持。
试试看这个链接：https://docs.qq.com/scenario/link.html?url=https%3A%2F%2Fwww.bd2020.com%2Fdh%2F14287.htm&pid=300000000$FtHzXMzVaJGA&cid=144115212906188709
我这里是这样的：
![image](https://github.com/axetroy/anti-redirect/assets/43476643/b2f858af-94cc-4600-bb20-b4046318f072)
@axetroy
