### ISSUE TITLE
在Google play没有效果

### ISSUE THREAD

**Issue by woyaojizhu8** [axetroy/anti-redirect#66]
点击应用详情页的 开发者->访问网站 ，仍然被重定向了

**Comment by axetroy** [comment]
感谢反馈，能否给个地址方便追踪问题

**Comment by woyaojizhu8** [comment]
例如 https://play.google.com/store/apps/details?id=com.mx.browser  里的  开发者->访问网站

**Comment by woyaojizhu8** [comment]
请问你还愿意更新这个脚本吗？我写了个简单脚本去除Google play的重定向，但是只在Chrome生效了，不知道为什么在Firefox不能生效，请问你可以看下吗？
https://gist.github.com/woyaojizhu8/9ad950a3a33727e86dfe8e5ae690eac5
另外，如果觉得可以的话，能否集成在你的脚本中？我只会写简单的几句js，不会你用的库，所以无法直接pull request

**Comment by axetroy** [comment]
@woyaojizhu8 
会更新的，也就这一两天，感谢帮助
